version: '3'

vars:
  DOCKER_COMPOSE: docker compose

tasks:
  # =============================================================================
  # Full Stack
  # =============================================================================
  default:
    desc: Show available tasks
    cmds:
      - task --list

  up:
    desc: Start all services (db, backend, frontend)
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d"

  down:
    desc: Stop all services
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  logs:
    desc: Tail logs for all services
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f"

  restart:
    desc: Restart all services
    cmds:
      - task: down
      - task: up

  build:
    desc: Build all Docker images
    cmds:
      - "{{.DOCKER_COMPOSE}} build"

  clean:
    desc: "⚠️  DESTRUCTIVE: Stop services and DELETE ALL DATA (removes volumes)"
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  # =============================================================================
  # Database
  # =============================================================================
  db:up:
    desc: Start only the database
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d db"

  db:logs:
    desc: Tail database logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f db"

  db:shell:
    desc: Open psql shell
    cmds:
      - "{{.DOCKER_COMPOSE}} exec db psql -U postgres -d housesearch"

  db:migrate:
    desc: Run database migrations
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend alembic upgrade head"

  db:migrate:create:
    desc: "Create a new migration (usage: task db:migrate:create -- 'migration name')"
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend alembic revision --autogenerate -m '{{.CLI_ARGS}}'"

  # =============================================================================
  # Backend
  # =============================================================================
  backend:up:
    desc: Start backend and database
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d db backend"

  backend:logs:
    desc: Tail backend logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f backend"

  backend:shell:
    desc: Open shell in backend container
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend bash"

  backend:test:
    desc: Run tests
    dir: backend
    cmds:
      - uv sync --extra test
      - uv run pytest tests/ -v

  backend:build:
    desc: Build backend Docker image
    cmds:
      - "{{.DOCKER_COMPOSE}} build backend"

  backend:restart:
    desc: Restart backend service
    cmds:
      - "{{.DOCKER_COMPOSE}} restart backend"

  # =============================================================================
  # Frontend
  # =============================================================================
  frontend:up:
    desc: Start frontend only
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d frontend"

  frontend:logs:
    desc: Tail frontend logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f frontend"

  frontend:build:
    desc: Build frontend Docker image
    cmds:
      - "{{.DOCKER_COMPOSE}} build frontend"

  frontend:restart:
    desc: Restart frontend service
    cmds:
      - "{{.DOCKER_COMPOSE}} restart frontend"

  frontend:dev:
    desc: Run frontend locally with npm (outside Docker)
    dir: frontend
    cmds:
      - npm install
      - npm run dev

  # =============================================================================
  # Scraper
  # =============================================================================
  scraper:run:
    desc: Run the scraper manually
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend python -m scraper.run"

  scraper:run:full:
    desc: Run the scraper manually (full)
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend python -m scraper.run --full"

  scraper:run:local:
    desc: Run scraper locally (requires venv)
    dir: backend
    cmds:
      - python -m scraper.run

  scraper:enrich:
    desc: Enrich all listings that don't have amenity scores
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend python -m scraper.enrich"

  # =============================================================================
  # Overpass (Local OSM)
  # =============================================================================
  overpass:init:
    desc: "Download BC data and initialize Overpass volume (one-time, ~15 min)"
    cmds:
      - echo "Downloading British Columbia OSM data..."
      - curl -L -o /tmp/bc.osm.pbf https://download.geofabrik.de/north-america/canada/british-columbia-latest.osm.pbf
      - echo "Initializing Overpass database (this takes ~15 minutes)..."
      - "{{.DOCKER_COMPOSE}} --profile enrichment run --rm -e OVERPASS_MODE=init -e OVERPASS_PLANET_URL=file:///db/region.osm.pbf -v /tmp/bc.osm.pbf:/db/region.osm.pbf overpass"
      - echo "Done! Overpass is ready. Start it with: task overpass:up"

  overpass:up:
    desc: Start Overpass service (requires overpass:init first)
    cmds:
      - "{{.DOCKER_COMPOSE}} --profile enrichment up -d overpass"

  overpass:down:
    desc: Stop Overpass service
    cmds:
      - "{{.DOCKER_COMPOSE}} --profile enrichment stop overpass"

  overpass:status:
    desc: Check Overpass API status
    cmds:
      - curl -s http://localhost:12345/api/status

  overpass:test:
    desc: Test Overpass with a sample query
    cmds:
      - |
        curl -s -X POST http://localhost:12345/api/interpreter \
          -d 'data=[out:json][timeout:5];node["amenity"="cafe"](around:500,49.2827,-123.1207);out;' \
          | head -c 500

  # =============================================================================
  # Development
  # =============================================================================
  dev:
    desc: Start all services in development mode with logs
    cmds:
      - "{{.DOCKER_COMPOSE}} up"

  dev:watch:
    desc: Start all services with hot reload (rebuilds images if needed)
    cmds:
      - "{{.DOCKER_COMPOSE}} -f docker-compose.yml -f docker-compose.dev.yml up"

  dev:backend:
    desc: Start db + backend with logs
    cmds:
      - "{{.DOCKER_COMPOSE}} up db backend"

  dev:frontend:
    desc: Start frontend with logs
    cmds:
      - "{{.DOCKER_COMPOSE}} up frontend"

  dev:frontend:watch:
    desc: Start frontend with hot reload
    cmds:
      - "{{.DOCKER_COMPOSE}} -f docker-compose.yml -f docker-compose.dev.yml up frontend"

  install:
    desc: Install all dependencies (backend + frontend)
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: Install backend Python dependencies
    dir: backend
    cmds:
      - pip install -r requirements.txt

  install:frontend:
    desc: Install frontend npm dependencies
    dir: frontend
    cmds:
      - npm install

  # =============================================================================
  # Kubernetes
  # =============================================================================
  k8s:apply:
    desc: Apply Kubernetes manifests
    cmds:
      - kubectl apply -k k8s/

  k8s:delete:
    desc: Delete Kubernetes resources
    cmds:
      - kubectl delete -k k8s/

  k8s:status:
    desc: Show status of domowik namespace
    cmds:
      - kubectl get all -n domowik

  k8s:logs:backend:
    desc: Tail backend pod logs
    cmds:
      - kubectl logs -f -l app=backend -n domowik

  k8s:logs:frontend:
    desc: Tail frontend pod logs
    cmds:
      - kubectl logs -f -l app=frontend -n domowik

  k8s:scraper:trigger:
    desc: Manually trigger the scraper CronJob
    cmds:
      - kubectl create job --from=cronjob/scraper scraper-manual-$(date +%s) -n domowik

  # =============================================================================
  # Docker Image Build (Production)
  # =============================================================================
  docker:build:
    desc: Build production Docker images
    cmds:
      - task: docker:build:backend
      - task: docker:build:frontend

  docker:build:backend:
    desc: Build backend production image
    cmds:
      - docker build -t domowik/backend:latest ./backend

  docker:build:frontend:
    desc: Build frontend production image
    cmds:
      - docker build -t domowik/frontend:latest ./frontend

  docker:push:
    desc: Push images to registry
    cmds:
      - docker push domowik/backend:latest
      - docker push domowik/frontend:latest
