version: '3'

vars:
  DOCKER_COMPOSE: docker compose

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # =============================================================================
  # Core Commands
  # =============================================================================
  up:
    desc: Start all services (db, backend, frontend)
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d"

  down:
    desc: Stop all services
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  logs:
    desc: Tail logs for all services
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f"

  build:
    desc: Build all Docker images
    cmds:
      - "{{.DOCKER_COMPOSE}} build"

  clean:
    desc: "Stop services and DELETE ALL DATA (removes volumes)"
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  # =============================================================================
  # Database
  # =============================================================================
  db:shell:
    desc: Open psql shell
    cmds:
      - "{{.DOCKER_COMPOSE}} exec db psql -U postgres -d housesearch"

  db:migrate:
    desc: Run database migrations
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend uv run alembic upgrade head"

  db:migrate:create:
    desc: "Create a new migration (usage: task db:migrate:create -- 'migration name')"
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend uv run alembic revision --autogenerate -m '{{.CLI_ARGS}}'"

  # =============================================================================
  # Backend
  # =============================================================================
  backend:logs:
    desc: Tail backend logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f backend"

  backend:shell:
    desc: Open shell in backend container
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend bash"

  backend:test:
    desc: Run backend tests locally
    dir: backend
    cmds:
      - uv sync --extra test
      - uv run pytest tests/ -v

  backend:restart:
    desc: Restart backend service
    cmds:
      - "{{.DOCKER_COMPOSE}} restart backend"

  # =============================================================================
  # Frontend
  # =============================================================================
  frontend:logs:
    desc: Tail frontend logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f frontend"

  frontend:dev:
    desc: Run frontend locally with npm (outside Docker)
    dir: frontend
    cmds:
      - npm install
      - npm run dev

  frontend:restart:
    desc: Restart frontend service
    cmds:
      - "{{.DOCKER_COMPOSE}} restart frontend"

  # =============================================================================
  # Scraper
  # =============================================================================
  scraper:run:
    desc: Run the scraper
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend uv run python -m scraper.run"

  scraper:run:full:
    desc: Run the scraper (full mode)
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend uv run python -m scraper.run --full"

  scraper:enrich:
    desc: Enrich listings with amenity scores
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend uv run python -m scraper.enrich"

  # =============================================================================
  # Overpass (Local OSM)
  # =============================================================================
  overpass:init:
    desc: "Download Vancouver data and initialize Overpass (~5 min)"
    cmds:
      - echo "Initializing Overpass with Vancouver area data (~57MB, ~5 min)..."
      - |
        {{.DOCKER_COMPOSE}} --profile enrichment run --rm \
          -e OVERPASS_MODE=init \
          -e OVERPASS_META=yes \
          -e OVERPASS_PLANET_URL=https://download.bbbike.org/osm/bbbike/Vancouver/Vancouver.osm.pbf \
          -e OVERPASS_PLANET_PREPROCESS="mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm.pbf" \
          overpass
      - docker run --rm -v domowik_overpass_db:/db alpine chmod 755 /db
      - "echo 'Done! Start Overpass with: task overpass:up'"

  overpass:init:bc:
    desc: "Download BC data and initialize Overpass (~30 min)"
    cmds:
      - echo "Initializing Overpass with British Columbia data (~1.1GB, ~30 min)..."
      - |
        {{.DOCKER_COMPOSE}} --profile enrichment run --rm \
          -e OVERPASS_MODE=init \
          -e OVERPASS_META=yes \
          -e OVERPASS_PLANET_URL=https://download.geofabrik.de/north-america/canada/british-columbia-latest.osm.pbf \
          -e OVERPASS_PLANET_PREPROCESS="mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm.pbf" \
          overpass
      - docker run --rm -v domowik_overpass_db:/db alpine chmod 755 /db
      - "echo 'Done! Start Overpass with: task overpass:up'"

  overpass:up:
    desc: Start Overpass service
    cmds:
      - "{{.DOCKER_COMPOSE}} --profile enrichment up -d overpass"

  overpass:down:
    desc: Stop Overpass service
    cmds:
      - "{{.DOCKER_COMPOSE}} --profile enrichment stop overpass"

  overpass:clean:
    desc: "Remove Overpass volume (requires re-init)"
    cmds:
      - "{{.DOCKER_COMPOSE}} --profile enrichment stop overpass || true"
      - "{{.DOCKER_COMPOSE}} --profile enrichment rm -f overpass || true"
      - docker volume rm domowik_overpass_db || true

  # =============================================================================
  # Kubernetes
  # =============================================================================
  k8s:apply:
    desc: Apply Kubernetes manifests
    cmds:
      - kubectl apply -k k8s/

  k8s:delete:
    desc: Delete Kubernetes resources
    cmds:
      - kubectl delete -k k8s/

  k8s:status:
    desc: Show status of domowik namespace
    cmds:
      - kubectl get all -n domowik

  k8s:logs:backend:
    desc: Tail backend pod logs
    cmds:
      - kubectl logs -f -l app=backend -n domowik

  k8s:logs:frontend:
    desc: Tail frontend pod logs
    cmds:
      - kubectl logs -f -l app=frontend -n domowik
